# Generated by Django 2.1.2 on 2018-11-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete='RESTRICT', to='app.Product')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
    ]
