# Generated by Django 2.1.2 on 2018-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='case_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
